spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
    username: postgres.mhloawudyrscwbokdmhb
    password: aSXIHKL01KMdBzH1
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update